# Los jugadores pueden herir y matar a otros jugadores.
PVP=true

# PVP is logged to admin chat
PVPLogToolChat=true

# PVP is logged to file
PVPLogToolFile=true

# El tiempo de juego se detiene cuando no hay jugadores conectados.
PauseEmpty=true

# Permitir o no el uso de /all en el chat global.
GlobalChat=true

ChatStreams=s,r,a,w,y,sh,f,all

# Los clientes pueden unirse sin tener ya una cuenta en la lista blanca. Si se establece en false, los administradores deben crear manualmente combinaciones de nombre de usuario y contraseña.
Open=true

# El primer mensaje de bienvenida visible en el panel de chat. Se mostrará inmediatamente después de que el jugador inicie la sesión. Puede utilizar colores RGB para cambiar el color del mensaje de bienvenida. También puede utilizar <LINE> para crear una línea separada dentro del texto. Utilice: <RGB:1,0,0> ¡Este mensaje se mostrará en rojo!
ServerWelcomeMessage=Welcome to Project Zomboid Multiplayer! <LINE> <LINE> To interact with the Chat panel: press Tab, T, or Enter. <LINE> <LINE> The Tab key will change the target stream of the message. <LINE> <LINE> Global Streams: /all <LINE> Local Streams: /say, /yell <LINE> Special Steams: /whisper, /safehouse, /faction. <LINE> <LINE> Press the Up arrow to cycle through your message history. Click the Gear icon to customize chat. <LINE> <LINE> Happy surviving!

ServerImageLoginScreen=

ServerImageLoadingScreen=

ServerImageIcon=

# Añade nombres de usuario desconocidos a la lista blanca cuando los jugadores se unen. Los clientes proporcionarán su propio nombre de usuario/contraseña al unirse. (Esto es para servidores Open=true)
AutoCreateUserInWhiteList=false

# Mostrar nombres de usuarios encima de la cabeza del personaje en el juego.
DisplayUserName=true

# Mostrar el nombre y el apellido sobre los jugadores en lugar del nombre de usuario.
ShowFirstAndLastName=false

UsernameDisguises=false

HideDisguisedUserName=false

SwitchZombiesOwnershipEachUpdate=false

# Obliga a cada nuevo jugador a aparecer en estas coordenadas de mundo x,y,z establecidas. Encuentra las coordenadas deseadas en map.projectzomboid.com. (Se ignora cuando es 0,0,0).
SpawnPoint=0,0,0

# Los jugadores pueden entrar y salir del PVP de forma individual. Un jugador sólo puede herir a otro cuando al menos uno de ellos está en modo PVP, como se muestra en la calavera y los huesos cruzados no ocultos de la izquierda de la pantalla. Cuando SafetySystem=false, los jugadores son libres de herir a los demás en cualquier momento si el PVP está activado.
SafetySystem=true

# Mostrar un icono de calavera sobre la cabeza de los jugadores que han entrado en el modo PVP.
ShowSafety=true

# El tiempo que tarda un jugador en entrar y salir del modo PVP. Mínimo=0 Máximo=1000 Por defecto=2
SafetyToggleTimer=2

# La rapidez con la que un jugador puede volver a entrar o salir del modo PVP, después de haberlo hecho recientemente. Mínimo=0 Máximo=1000 Por defecto=3
SafetyCooldownTimer=3

# Mínimo=0 Máximo=60 Por defecto=60
SafetyDisconnectDelay=60

# Tipos de objetos con los que aparecen los nuevos jugadores. Separa varios tipos de objetos con comas. Ejemplo: Base.Axe,Base.Bag_BigHikingBag
SpawnItems=

# Puerto inicial por defecto para los datos del jugador. Si es UDP, este es uno de los dos puertos utilizados. Mínimo=0 Máximo=65535 Por defecto=16261
DefaultPort=16261

# Mínimo=0 Máximo=65535 Por defecto=16262
UDPPort=16262

# El reinicio de ID determina si el servidor ha sufrido un reinicio simple. Si este número coincide con el del cliente, éste debe crear un nuevo personaje. Se utiliza junto con PlayerServerID. Se recomienda encarecidamente hacer una copia de seguridad de estos ID en algún lugar Mínimo=0 Máximo=2147483647 Por defecto=193833209
ResetID=2527679

# Enter the mod loading ID here. It can be found in \Steam\steamapps\workshop\modID\mods\modName\info.txt
Mods=ATA_Bus;tsarslib;ATA_Mustang_x4;ATA_Mustang;Bandits2

# Enter the foldername of the mod found in \Steam\steamapps\workshop\modID\mods\modName\media\maps\
Map=Muldraugh, KY

# Expulsa a los jugadores que sus archivos de juego no coinciden con los del servidor.
DoLuaChecksum=true

DenyLoginOnOverloadedServer=true

# Muestra el servidor en el navegador del juego. (Nota: los servidores habilitados para Steam siempre son visibles en el navegador de servidores de Steam).
Public=false

# Nombre del servidor que se muestra en el navegador del juego y, en su caso, en el navegador de Steam.
PublicName=My PZ Server

# Descripción mostrada en el navegador del servidor público del juego. Al escribir   se creará una nueva línea en su descripción.
PublicDescription=

# Maximum number of players that can be on the server at one time. This excludes admins.
# WARNING: Server player counts above 32 will potentially result in poor map streaming and desync. Please advance with caution. Mínimo=1 Máximo=100 Por defecto=32
MaxPlayers=32

# Ping limit, in milliseconds, before a player is kicked from the server. (Set to 0 to disable) Mínimo=0 Máximo=2147483647 Por defecto=0
PingLimit=0

# Items will not respawn in buildings that players have claimed as a safehouse
SafehousePreventsLootRespawn=true

# Eliminar las cuentas de los jugadores de la lista blanca después de la muerte. Esto evita que los jugadores creen un nuevo personaje después de la muerte en los servidores Open=false
DropOffWhiteListAfterDeath=false

# All forms of fire are disabled - except for campfires
NoFire=false

# If checked, every time a player dies a global message will be displayed in the chat
AnnounceDeath=false

# If checked, every time an animal dies a global message will be displayed in the chat
AnnounceAnimalDeath=false

# Las partes cargadas del mapa se guardan después de que haya pasado este número de minutos en el mundo real. (El mapa suele guardarse sólo cuando los clientes abandonan una zona cargada). Mínimo=0 Máximo=2147483647 Por defecto=0
SaveWorldEveryMinutes=0

# Tanto los administradores como los jugadores pueden reclamar refugios.
PlayerSafehouse=false

# Sólo los administradores pueden reclamar refugios
AdminSafehouse=false

# Permitir que los miembros ajenos al refugio entren en él sin ser invitados.
SafehouseAllowTrepass=true

# Permitir que el fuego dañe los refugios.
SafehouseAllowFire=true

# Permitir que los miembros ajenos al refugio se puedan llevar objetos del mismo.
SafehouseAllowLoot=true

# Los jugadores reaparecerán en el refugio del que formaban parte antes de morir.
SafehouseAllowRespawn=false

# Los jugadores deben haber sobrevivido este número de días en el juego antes de poder reclamar un refugio. Mínimo=0 Máximo=2147483647 Por defecto=0
SafehouseDaySurvivedToClaim=0

# Los jugadores son eliminados automáticamente de un refugio que no hayan visitado durante tantas horas del mundo real. Mínimo=0 Máximo=2147483647 Por defecto=144
SafeHouseRemovalTime=144

# Controla si los jugadores pueden reclamar edificios no residenciales.
SafehouseAllowNonResidential=false

SafehouseDisableDisguises=true

# Mínimo=0 Máximo=2147483647 Por defecto=20000
MaxSafezoneSize=20000

# Permitir a los jugadores destruir objetos del mundo con almádenas
AllowDestructionBySledgehammer=true

# Permite a los jugadores destruir objetos del mundo sólo en su refugio (requiere que AllowDestructionBySledgehammer sea verdadero).
SledgehammerOnlyInSafehouse=false

War=true

# Time in seconds before the war starts. Mínimo=60 Máximo=2147483647 Por defecto=600
WarStartDelay=600

# War duration in seconds. Mínimo=60 Máximo=2147483647 Por defecto=3600
WarDuration=3600

# Safehouse hit points limit. Mínimo=0 Máximo=2147483647 Por defecto=3
WarSafehouseHitPoints=3

# ServerPlayerID determina si un personaje es de otro servidor, o de un solo jugador. Este valor puede cambiarse mediante reinicios simples. Si este número coincide con el cliente, el cliente debe crear un nuevo personaje. Esto se utiliza junto con ResetID. Se recomienda encarecidamente hacer una copia de seguridad de estos ID en algún lugar.
ServerPlayerID=

# The port for the RCON (Remote Console) Mínimo=0 Máximo=65535 Por defecto=27015
RCONPort=27015

# RCON password (Pick a strong password)
RCONPassword=

# Enables global text chat integration with a Discord channel
DiscordEnable=false

# Discord bot access token
DiscordToken=

# The Discord chat channel name
DiscordChatChannel=

# The Discord logs channel name
DiscordLogChannel=

# The Discord commands channel name
DiscordCommandChannel=

# The Slack incoming webhook URL
WebhookAddress=

# Los clientes deben conocer esta contraseña para unirse al servidor. (Se ignora cuando se aloja un servidor mediante el botón Anfitrión).
Password=

# Limita el número de cuentas diferentes que un solo jugador de Steam puede crear en este servidor. Se ignora cuando sea un servidor de Steam. Mínimo=0 Máximo=2147483647 Por defecto=0
MaxAccountsPerUser=0

# Habilitar el modo de juego cooperativo o de pantalla dividida
AllowCoop=true

# Los jugadores pueden dormir cuando su superviviente esté cansado, pero no necesitan dormir.
SleepAllowed=false

# Los jugadores se cansan y necesitan dormir. (Se ignora si SleepAllowed=false).
SleepNeeded=false

# WIP: Activating this setting may cause visual desynchronization of player positions.
KnockedDownAllowed=false

SneakModeHideFromOtherPlayers=true

UltraSpeedDoesnotAffectToAnimals=false

# List Workshop Mod IDs for the server to download. Each must be separated by a semicolon. Example: WorkshopItems=514427485;513111049
WorkshopItems=

# Mostrar los nombres de usuario y avatares de Steam en la lista de jugadores. Puede ser true (visible para todos), false (no visible para nadie), o admin (visible sólo para los administradores).
SteamScoreboard=false

# Enable the Steam VAC system
SteamVAC=true

# Intenta configurar una puerta de enlace a internet con UPnP para que establezca automáticamente reglas de reenvío de puertos. El servidor volverá a los puertos por defecto si esto falla.
UPnP=true

# VOIP is enabled when checked
VoiceEnable=true

# The minimum tile distance over which VOIP sounds can be heard. Mínimo=0,00 Máximo=100000,00 Por defecto=10,00
VoiceMinDistance=10.0

# The maximum tile distance over which VOIP sounds can be heard. Mínimo=0,00 Máximo=100000,00 Por defecto=100,00
VoiceMaxDistance=100.0

# Toggle directional audio for VOIP
Voice3D=true

# Mínimo=10,00 Máximo=150,00 Por defecto=70,00
SpeedLimit=70.0

LoginQueueEnabled=false

# Mínimo=20 Máximo=1200 Por defecto=60
LoginQueueConnectTimeout=60

# Set the IP from which the server is broadcast. This is for network configurations with multiple IP addresses, such as server farms
server_browser_announced_ip=

# Los jugadores pueden reaparecer en el juego en las coordenadas donde murieron.
PlayerRespawnWithSelf=false

# Los jugadores pueden reaparecer en el juego en la ubicación de otro jugador en pantalla dividida/Remote Play.
PlayerRespawnWithOther=false

# Governs how fast time passes while players sleep. Value multiplies the speed of the time that passes during sleeping. Mínimo=1,00 Máximo=100,00 Por defecto=40,00
FastForwardMultiplier=40.0

# Safehouse acts like a normal house if a member of the safehouse is connected (so secure when players are offline)
DisableSafehouseWhenPlayerConnected=false

# Players can create factions when true
Faction=true

# Players must survive this number of in-game days before being allowed to create a faction Mínimo=0 Máximo=2147483647 Por defecto=0
FactionDaySurvivedToCreate=0

# Number of players required as faction members before the faction owner can create a group tag Mínimo=1 Máximo=2147483647 Por defecto=1
FactionPlayersRequiredForTag=1

# Desactiva las transmisiones de radio de los jugadores con un nivel de acceso
DisableRadioStaff=false

# Desactiva las transmisiones de radio de los jugadores con nivel de acceso 'admin'
DisableRadioAdmin=true

# Desactiva las transmisiones de radio de los jugadores con nivel de acceso 'gm'
DisableRadioGM=true

# Desactiva las transmisiones de radio de los jugadores con nivel de acceso 'overseer'
DisableRadioOverseer=false

# Desactiva las transmisiones de radio de los jugadores con nivel de acceso 'moderador'
DisableRadioModerator=false

# Desactiva las transmisiones de radio de los jugadores invisibles
DisableRadioInvisible=true

# Lista separada por punto y coma de los comandos que no se escribirán en el registro del servidor cmd.txt. Por ejemplo:  -vehicle. Introducir * significa NO escribir ningún comando de vehículo. Introduciendo:  +vehicle.installPart significa que SI se escribe ese comando
ClientCommandFilter=-vehicle.*;+vehicle.damageWindow;+vehicle.fixPart;+vehicle.installPart;+vehicle.uninstallPart

# Lista separada por punto y coma de las acciones que se escribirán en el registro del servidor ClientActionLogs.txt.
ClientActionLogs=ISEnterVehicle;ISExitVehicle;ISTakeEngineParts;

# Seguimiento de los cambios en los niveles de habilidades de los jugadores en el registro del servidor PerkLog.txt
PerkLogs=true

# Número máximo de artículos que se pueden colocar en un contenedor.  Cero significa que no hay límite. (NOTA: Esto incluye artículos individuales pequeños como clavos. Un límite de 50 significará que sólo se pueden almacenar 50 clavos). Mínimo=0 Máximo=9000 Por defecto=0
ItemNumbersLimitPerContainer=0

# Número de días antes de que se eliminen las manchas de sangre antiguas.
# La eliminación se produce cuando se cargan los trozos de mapa.
# Cero significa que nunca desaparecerán Mínimo=0 Máximo=365 Por defecto=0
BloodSplatLifespanDays=0

# Permitir el uso de caracteres no ASCII (cirílico, etc.) en los nombres de usuario
AllowNonAsciiUsername=false

BanKickGlobalSound=true

# Si se activa, cuando HoursForCorpseRemoval se activa, también eliminará los cadáveres de los jugadores del suelo.
RemovePlayerCorpsesOnCorpseRemoval=false

# Si es activado, el jugador puede utilizar el botón "eliminar todo" en las papeleras.
TrashDeleteAll=false

# Si es activado, el jugador puede volver a golpear cuando es golpeado por otro jugador.
PVPMeleeWhileHitReaction=false

# Si está activado, los jugadores tendrán que pasar el ratón por encima de alguien para ver su nombre.
MouseOverToSeeDisplayName=true

# Si está activado, oculta automáticamente al jugador que no puedes ver (como los zombis).
HidePlayersBehindYou=true

# Daño añadido a los ataques cuerpo a cuerpo en PVP. Mínimo=0,00 Máximo=500,00 Por defecto=30,00
PVPMeleeDamageModifier=30.0

# Daño añadido a los ataques a distancia en PVP. Mínimo=0,00 Máximo=500,00 Por defecto=50,00
PVPFirearmDamageModifier=50.0

# Modifica el rango de atracción de los zombis hacia los coches. (Los valores más bajos pueden ayudar con el retraso). Mínimo=0,00 Máximo=10,00 Por defecto=0,50
CarEngineAttractionModifier=0.5

# Controla si los jugadores chocan (y derriban) a otros jugadores cuando corren entre ellos.
PlayerBumpPlayer=false

# Controla la visualización de los jugadores remotos en el mapa del juego. 1=Oculto 2=Amigos 3=Todos Mínimo=1 Máximo=3 Por defecto=1
MapRemotePlayerVisibility=1

# Mínimo=1 Máximo=300 Por defecto=5
BackupsCount=5

BackupsOnStart=true

BackupsOnVersionChange=true

# Mínimo=0 Máximo=1500 Por defecto=0
BackupsPeriod=0

# Disables vehicle towing
DisableVehicleTowing=false

# Disables trailer towing
DisableTrailerTowing=false

# Disables burnt vehicle towing
DisableBurntTowing=false

# Path to the file with the list of words to be prohibited. Each word must be on a separate line
BadWordListFile=

# Path to the file with the list of words that should be allowed, even if they contain bad word. Each word should be on a separate line.
GoodWordListFile=

# What to do with the sender of a bad word in the chat: 1 - ban, 2 - kick, 3 - record the violation in the database, 4 - mute
BadWordPolicy=3

# The symbol or piece of text that will replace the bad word
BadWordReplacement=[HIDDEN]

# Disables safety system anti-cheat protection.
AntiCheatSafety=4

AntiCheatMovement=4

# Disables character hit anti-cheat protection.
AntiCheatHit=4

# Disables packet checks anti-cheat protection.
AntiCheatPacket=4

# Disables player permissions anti-cheat protection.
AntiCheatPermission=4

# Disables player XP anti-cheat protection.
AntiCheatXP=4

# Disables fire checks anti-cheat protection.
AntiCheatFire=4

# Disables safehouse anti-cheat protection.
AntiCheatSafeHouse=4

# Disables recipe checks anti-cheat protection.
AntiCheatRecipe=4

AntiCheatPlayer=4

# Disables checksum anti-cheat protection.
AntiCheatChecksum=4

# Disables item checks anti-cheat protection.
AntiCheatItem=4

AntiCheatServerCustomization=4

# Sets the multiplayer update period in seconds. Statistics is disabled if value is 0. Mínimo=0 Máximo=10 Por defecto=1
MultiplayerStatisticsPeriod=1

# Disables scoreboard.
DisableScoreboard=false

# Hides admins in the player list.
HideAdminsInPlayerList=false

# The worldgen seed used to generate the world.
# If you want to change this, put a new value in and delete map_worldgen.bin in your save directory.
Seed=

UsePhysicsHitReaction=false

# Mínimo=64 Máximo=1024 Por defecto=200
ChatMessageCharacterLimit=200

# Mínimo=1 Máximo=30 Por defecto=3
ChatMessageSlowModeTime=3